### ISSUE TITLE
track color options

### ISSUE THREAD

**Issue by sarahcd** [movestore/animation-moveVis#4]
Currently the only option is to color by track ID. We should revisit what additional options are possible. In order of decreasing priority (IMO):
* Color by Animal ID: If data have been segmented into multiple tracks per animal in previous apps, the current option (track ID) will be misleading if they assume a track = an animal.
* Single color: Allowing a single color for all tracks can make a cleaner animation and eliminate need for a legend.
* Color by select attribute from the dataframe: This comes from the existing request to color by species, but a single solution could allow coloring by sex, population, etc. 

Seems like we need a step to somehow assign a color attribute. I'm not sure if there are any recent updates or plans to integrate any of this in movevis. [Here is one example](https://gist.github.com/16EAGLE/2a2ad684b3ea2c874cfcb5b364bc573c) but rather customized. Maybe this could be a job for a different (new) app, that could assign colors in the df that might be used by other Apps as well?

**Comment by andreakoelzsch** [comment]
Thanks for the suggestions!
- with animal ID not being uniform from Movebank this feature is rather difficult to get working correctly. I have the hope that it would be improved if we adapt this App to move2. I will keep these in mind for it.
- the legend can be deactivated already, single colour should not be a problem.
- I think that could be possible with move2, but people would have to type in the correct attribute names from the cargo agent. would that be ok?

I would probably have to ask Jakob, if he is planning to rework moveVis for sf, then an adaption will come anyway. To make a new App, maybe, lets discuss that in Gardenier.

**Comment by sarahcd** [comment]
Can we go through some examples using the Animal ID? It seems it should be possible using the same "Animal Names" that seem to be reliably reported in the cargo agent across workflows.

**Comment by andreakoelzsch** [comment]
Hi @sarahcd, I have now taken the time to look into the details of this App again and submitted a new version with additional option to colour also uniformly, by animal ID and by any other attribute of the data. The animal ID is extracted as in the cargo agent, and if neither individual.local,identifier or local.identifier are available it defaults to track ID. THe legend is not optimal, as it still shows the track names, but with the correct colours. Please try it out, we can talk more about it. I have not got any feedback from Jakob, unfortuantely. Merci :)
