### ISSUE TITLE
"Error in evaluating the argument 'x' in selecting a method for function 'moveStack'"

### ISSUE THREAD

**Issue by aklohr** [movestore/animation-moveVis#9]
Tried the _move2_ version of the animation app and got this error immediately upon running:
![image](https://github.com/movestore/animation-moveVis/assets/112666849/4d99c61f-afcb-4dfd-a248-cf60a0516c2f)

My workflow using all move2 apps (also tried removing summary statistics app and I still got an error):
![image](https://github.com/movestore/animation-moveVis/assets/112666849/bdf3c57c-c98f-4ad6-9e84-a5e86c8e87b6)

I am using the same settings for the animation app that I used in the previous _move1_ version, which runs successfully (just ran it in an old workflow).

Logs:
![image](https://github.com/movestore/animation-moveVis/assets/112666849/a542612a-60f0-4756-af0e-12fb280074cf)

Movebank study: Long-billed Curlew Migration from the Intermountain West (ID: 42451582)
Animals: 6C - Hest1-M - ND, 6E - Turb-F - SD, 6A - Turbo - ND, 6K - - ND

**Comment by andreakoelzsch** [comment]
Hi @aklohr , I could not reproduce the error, as I dont know the settings that you have used in the Movebank App. However, I have just shared a workflow with you on MoveApps that works. Maybe go ahead and us it. still, it might be worth that you share that workflow with the above error with me on MoveApps. Thanks!

**Comment by aklohr** [comment]
Hi @andreakoelzsch , I've just shared the workflow with you so you can see which settings I used in the Animation App. In the Workflow Instance details I provided some notes about which settings I tested. All resulted in the same error message.

**Comment by sarahcd** [comment]
Hi @andreakoelzsch , I think it's worth investigating the resolution setting. I played around with the workflow you shared. I can't return to the original to be absolutely sure, but from my notes of what I did, simply updating the resolution setting from 0.2 to 0.8 leads to an error. Likewise, if I change the resolution setting from 0.8 to 0.2 in the other workflow I'm preparing, it runs. The outputs are very blurry so I'd like to increase it.

**Comment by andreakoelzsch** [comment]
Hi @aklohr @sarahcd , I have updated to force movestack structure to the data, but with the tracks that you have provided Ashely, I keep having the error, and cannot solve it.
@annescharf : it happens in line 20 https://github.com/movestore/animation-moveVis/blob/main/RFunction.R, I guess the align_move() has problems with the data somehow, I add the file here.

What is important to note is that Ashley had downloaded GPS AND Argos data with the preceding Movebank App. If I only select GPS the Animation App runs without error. Maybe that is a good way of working with it for now.

**Comment by andreakoelzsch** [comment]
[data_movestack.zip](https://github.com/movestore/animation-moveVis/files/14956171/data_movestack.zip)

**Comment by andreakoelzsch** [comment]
Unfortunately, the fix did not work for Ashley's data as expected. There is not the below screenshotted Error (which I do not get locally, but in moveApps). 
![grafik](https://github.com/movestore/animation-moveVis/assets/65662928/4128a0b1-baf2-45e1-903c-8d32549b61ee)

**Comment by andreakoelzsch** [comment]
@aklohr @sarahcd 
Hi Ashley and Sarah, I have looked intothe error in quite some detail now. And, it is not so easy to solve generally. The paramter "Resolution of background map" has quite some influence on the performance of the App and depends strongly on the extent of the data. I have updated the App to take into account some possible changes of moveVis parameters to take into account data extent. However, you will still have to try a bit with the resolution parameter. In some test data sets of mine it gave an error with too high value (1) - memory max, in others it gave an error with too low value (0.2) - the above row1_... error. I have added this notion to the settings description and documentation. Ashley's workflow is running now (I share it back again in 2 min), but please beware that the extent is rather big here. In about 3-4 weeks, I hope with the better hardware on MPDCF that will be better.
Another change -> I have gone back to OSM maps (two options, topogr. and streets), with the help of Jakob we might be able to retreive the OSM maps from the MoveApps local mirror, but for now it uses the public one (which might lead to empty background if asked too often - there should be a limit of download numbers per day).
